name: Continuous Integration

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    name: Tests
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - uses: c-hive/gha-yarn-cache@v1

    - name: Install node modules
      run: |
        yarn install
    - name: Run linter
      run: |
        yarn lint
    - name: Run tests
      run: |
        yarn test
